### ISSUE TITLE
CPU cost for custom pricing not matching the screenshot

### ISSUE THREAD

**Issue by kastl-ars** [kubecost/docs#1138]
The CPU cost in the "custom pricing" section is not matching the one from the screen shot.

https://docs.kubecost.com/architecture/pricing-sources-matrix#custom-pricing

https://github.com/kubecost/docs/blob/35d28fabdb6682eb009a4bd95adf0a292596e54c/architecture/pricing-sources-matrix.md?plain=1#L74

The screenshot has roughly `23.08` for the CPU price, the YAML snippet (see below) has `28.0`.

```yaml
kubecostProductConfigs:
  customPricesEnabled: true
  defaultModelPricing:
    enabled: true
    CPU: 28.0 # Single core per month cost
    spotCPU: 4.86 # Single core per month cost
    RAM: 3.09 # GB per month cost
    spotRAM: 0.65 # GB per month cost
    GPU: 693.50 # per month cost
    spotGPU: 225.0 # per month cost
    storage: 0.04 # per GB per month cost
    zoneNetworkEgress: 0.01 # per GB per month cost
    regionNetworkEgress: 0.01 # per GB per month cost
    internetNetworkEgress: 0.12 # per GB per month cost
```
