### ISSUE TITLE
Deployment controllers and service section data not showing up in kubecost dashboard

### ISSUE THREAD

**Issue by mpsanj** [kubecost/docs#149]
Hi Team, we have been looking into kubecost for getting cost in AKS at namespace level, and it sounds like a good fit for our needs.
Deployment controller aren't be identified,  gets into a generic section called no controllers as shown in the image, why is this happening ?
<img width="1197" alt="kubecost-screenshot" src="https://user-images.githubusercontent.com/43144863/143174569-52bc7aae-9b5d-4da3-a0f6-0cd3398d75ff.png">

We are passing a custom values file with the helm chart kubecost/cost-analyzer, which disables prometheus, grafana and adds an ingress resource

```
global:
  grafana:
    domainName: grafana-xxx.com
    enabled: false
    proxy: false
    scheme: http
  notifications:
    alertmanager:
      enabled: false
  prometheus:
    enabled: false
    fqdn: http://prometheus-server.monitoring.svc.cluster.local
  thanos:
    enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  paths: ["/"] 
  hosts:
    - kubecost.xx.com
  tls: []

prometheus:
  alertmanager:
    enabled: false
    persistentVolume:
      enabled: false
  nodeExporter:
    enabled: true

networkCosts:
  enabled: true

kubecostProductConfigs:
  azureStorageSecretName: kubecost-storage
```

Chart version:  cost-analyzer-1.86.1
Not sure why the deployment controllers and service section doesnt show up ?

[kubecost-bug-report-1637727299197.txt](https://github.com/kubecost/docs/files/7592706/kubecost-bug-report-1637727299197.txt)

Thank You !

gz#1077
