### ISSUE TITLE
Simplify "Attach via pod Annotation on EKS" process

### ISSUE THREAD

**Issue by linhlam-kc** [kubecost/docs#353]
This step https://github.com/kubecost/docs/blob/main/aws-cloud-integrations.md#step-4-attaching-iam-permissions-to-kubecost need to be simplified by providing AWS CLI  commands to help customer following the instructions easier.

**Comment by bstuder99** [comment]
Can get started on this soon. @linhlam-kc couple questions for you about this procedure:
* Would AWS CLI commands be considered an alternative fourth option compared to the other three? Or is using AWS CLI commands a means of performing any of the three methods?
* Are there reasons a user might still prefer to use one of the existing methods?

**Comment by linhlam-kc** [comment]
Thank you @bstuder99 It is going to be the fourth option which simplify the process further. I actually have a similar instructions for Solutions team repo at : https://github.com/kubecost/poc-common-configurations/tree/main/aws-attach-roles#step-5-create-required-iam-service-accounts

Are there reasons a user might still prefer to use one of the existing methods? --> Yes, users may want to understand the manual steps to build their own automation script or simply prefer using AWS console over AWS CLI tools.

**Comment by bstuder99** [comment]
So a few things I would consider here:
1. We may need to list eksctl and AWS CLI as a prereq, I know it's fairly common in general AWS use, but the rest of the existing doc doesn't necessarily rely on it, so unless we add it to the very top of the doc, it should be added here somewhere.
2. In the example in Step 5 from the link you provided, I'm curious about the inclusion of Thanos, for the same reason as above with eksctl, that the rest of the doc doesn't really touch this concept.

**Comment by linhlam-kc** [comment]
Hi @bstuder99 ,sorry  for late reply here, somehow I missed your message. Regarding to your questions:

1. Agreed, we can add them as a prereq.
2. The documentation I shared includes the config to set up Thanos for multi-cluster set up. So the information that is related to Thanos need to be removed such as:
- The entire Step 1
- In step 3:
`aws iam create-policy --policy-name kubecost-s3-thanos-policy --policy-document file://kubecost-s3-thanos-policy.json`
- In step 5: 
```bash
eksctl create iamserviceaccount \
    --name kubecost-serviceaccount-thanos \
    --namespace kubecost \
    --cluster ${YOUR_CLUSTER_NAME} --region ${AWS_REGION} \
    --attach-policy-arn arn:aws:iam::1111111111:policy/kubecost-s3-thanos-policy \
    --override-existing-serviceaccounts \
    --approve
```
- In step 7: 
```
Additional Clusters
helm upgrade --install kubecost --repo https://kubecost.github.io/cost-analyzer/ cost-analyzer \
--namespace kubecost \
-f https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/master/cost-analyzer/values-thanos.yaml \
-f values-amazon-secondary.yaml
```
Additionally, The `values-amazon-primary.yaml` should look as follows:
```yaml
serviceAccount:
  create: false # Set this to false if you're bringing your own service account.
  # annotations: {}
  name: kubecost-serviceaccount-cur-athena-thanos
kubecostProductConfigs:
  # projectID: "AWS_kubecostProductConfigs_projectID"
  cloudIntegrationSecret: cloud-integration
  # clustername should be unique for all clusters
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false #not needed for eval
  # awsSpotDataRegion: AWS_kubecostProductConfigs_awsSpotDataRegion
  # awsSpotDataBucket: AWS_kubecostProductConfigs_awsSpotDataBucket
  # awsSpotDataPrefix: dev
  # serviceKeySecretName: aws-service-key # Used for Spot Data Feed and Unattached Disks/IP Addresses
# kubecostMetrics:
  # emitKsmV1Metrics: true # emit all KSM metrics in KSM v1. https://github.com/kubecost/docs/blob/main/ksm-metrics.md
  # emitKsmV1MetricsOnly: false # emit only the KSM metrics missing from KSM v2. Advanced users only. https://github.com/kubecost/docs/blob/main/ksm-metrics.md
kubecostModel:
  containerStatsEnabled: true
  cloudCost:
    enabled: true # Set to true to enable CloudCost view that gives you visibility of your Cloud provider resources cost
  etlCloudAsset: false # Set etlCloudAsset to false when cloudCost.enabled is true to reduce cluster resources consumption. Set to true to enable kubecost to include out-of-cluster cloud resources  (uses more memory)
prometheus:
  # Note: Even though we are disabling our bundled version of kube-state-metrics, Kubecost still emits v1 metrics.
  # Care will need to be taken in environments that already have KSM deployed.
  # For more information, see: https://github.com/kubecost/docs/blob/main/ksm-metrics.md
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    disabled: true
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: kubecostProductConfigs_clusterName
  # Disable node exporter+service account if cluster/node rightsizing recommendations are not required
  # In addition, node-export must be disabled if there is an existing daemonset: https://guide.kubecost.com/hc/en-us/articles/4407601830679-Troubleshoot-Install#a-name-node-exporter-a-issue-failedscheduling-kubecost-prometheus-node-exporter
  # nodeExporter:
  #   enabled: false
```
